"""Emit a Swift GameContent literal from an analyzed+annotated work-store game.

Lets the iOS app play a real pipeline game the same way it plays the M1 sample
(SampleGames.gameOfTheCentury). Maps legal_evals -> candidateEvals: [String:Int],
clamping mate scores to a large cp (the M1 Swift model has no mate field yet).

Usage: python tools/gen_app_game.py <game_id> <SwiftVarName>
   ->  ../App/Sources/Features/GuessSession/AppGame_<SwiftVarName>.swift
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import store

MATE_BASE = 30000  # mate clamp so a mating move outranks any cp (TECH_SPEC §3.2 clamp)


def clamp_cp(entry: dict) -> int:
    mate = entry.get("mate")
    if mate is not None:
        return (MATE_BASE - mate * 100) if mate > 0 else (-MATE_BASE - mate * 100)
    return int(entry.get("cp") or 0)


def swift_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(game_id: str, var: str) -> int:
    game = store.load_game(game_id)
    start_fen = game.moves[0].fen_before if game.moves else ""

    rows = []
    for m in game.moves:
        if m.is_guess_point and m.legal_evals:
            evals = ", ".join(f'{swift_str(u)}: {clamp_cp(e)}'
                              for u, e in m.legal_evals.items())
            evals_literal = "[" + evals + "]"
            ann = swift_str(m.annotation) if m.annotation else "nil"
            tags = "[" + ", ".join(f".{t}" for t in (m.tags or ["tactical"])) + "]"
            rows.append(
                f"        ContentMove(ply: {m.ply}, uci: {swift_str(m.uci)}, "
                f"san: {swift_str(m.san)}, fenBefore: {swift_str(m.fen_before)}, "
                f"mover: .{m.mover}, isGuessPoint: true, tags: {tags}, "
                f"annotation: {ann}, candidateEvals: {evals_literal}, "
                f"difficulty: {m.difficulty})"
            )
        else:
            rows.append(
                f"        ContentMove(ply: {m.ply}, uci: {swift_str(m.uci)}, "
                f"san: {swift_str(m.san)}, fenBefore: {swift_str(m.fen_before)}, "
                f"mover: .{m.mover}, isGuessPoint: false, tags: [], "
                f"annotation: nil, candidateEvals: [:])"
            )

    moves_block = ",\n".join(rows)
    swift = f"""// GENERATED by pipeline/tools/gen_app_game.py from analyzed work-store data.
// Real Stockfish evals + grounded annotations (one-off preview content). Do not edit by hand.

import Foundation

extension SampleGames {{
    static let {var} = GameContent(
        id: {swift_str(game.id)},
        white: {swift_str(game.white)},
        black: {swift_str(game.black)},
        event: {swift_str(game.event)},
        year: {game.year or 0},
        result: {swift_str(game.result)},
        heroColor: .{game.hero_color or 'white'},
        title: {swift_str(game.title or game.id)},
        narrativeIntro: {swift_str(game.narrative_intro or '')},
        startFen: {swift_str(start_fen)},
        moves: [
{moves_block}
        ]
    )
}}
"""

    out = os.path.normpath(os.path.join(
        os.path.dirname(__file__), "..", "..", "App", "Sources",
        "Features", "GuessSession", f"AppGame_{var}.swift",
    ))
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(swift)
    print(f"Wrote {out}: {len(game.moves)} plies, "
          f"{sum(1 for m in game.moves if m.is_guess_point)} guess points.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
