"""Generate the M1 hardcoded sample game as a compile-checked Swift literal.

M1 needs ONE hand-prepared master game to exercise the GuessSession loop without
waiting on the content pipeline (ROADMAP M1). Board data (uci / san / fen_before per
ply) is produced by python-chess so every move is guaranteed legal — chess correctness
is sacred (CLAUDE.md hard rule #5). Evals here are PLACEHOLDERS: M1 has no engine data,
so the master move is marked best (delta 0) and a couple of points get one hand-set
near-equal alternative just so the "Equally strong" band is reachable in the demo.
Real per-move evals (legal_evals, all legal moves) arrive with the M2 pipeline.

Run:  python tools/gen_sample_game.py
Emits: ../App/Sources/Features/GuessSession/SampleGame.swift
"""

from __future__ import annotations

import os

import chess

# Byrne vs. Fischer, "The Game of the Century", New York 1956. Fischer (Black) is the hero.
GAME_SAN = (
    "Nf3 Nf6 c4 g6 Nc3 Bg7 d4 O-O Bf4 d5 Qb3 dxc4 Qxc4 c6 e4 Nbd7 Rd1 Nb6 "
    "Qc5 Bg4 Bg5 Na4 Qa3 Nxc3 bxc3 Nxe4 Bxe7 Qb6 Bc4 Nxc3 Bc5 Rfe8+ Kf1 Be6 "
    "Bxb6 Bxc4+ Kg1 Ne2+ Kf1 Nxd4+ Kg1 Ne2+ Kf1 Nc3+ Kg1 axb6 Qb4 Ra4 Qxb6 Nxd1 "
    "h3 Rxa2 Kh2 Nxf2 Re1 Rxe1 Qd8+ Bf8 Nxe1 Bd5 Nf3 Ne4 Qb8 b5 h4 h5 Ne5 Kg7 "
    "Kg1 Bc5+ Kf1 Ng3+ Ke1 Bb4+ Kd1 Bb3+ Kc1 Ne2+ Kb1 Nc3+ Kc1 Rc2#"
).split()

# Black plies (ply = 2 * move_number) chosen as guess points for the M1 demo.
# Includes the famous 11...Na4!!, 17...Be6!! (queen sac), and the final 41...Rc2#.
GUESS_POINT_PLIES = {22, 26, 34, 36, 48, 50, 82}

# Hand-set near-equal alternative (placeholder) at a couple of points so the demo can
# show the yellow "Equally strong / good" band. Maps ply -> eval cp penalty for the alt.
ALT_PENALTY_BY_PLY = {34: 50, 48: 60}

TITLE = "The Game of the Century"
NARRATIVE = (
    "A 13-year-old Bobby Fischer faces Donald Byrne in New York, 1956. "
    "You play Black. Watch for the move that stunned the chess world."
)


def tag_for(board: chess.Board, move: chess.Move, san: str) -> str:
    if "#" in san or "+" in san:
        return "tactical"
    if board.is_capture(move):
        return "tactical"
    return "positional"


def swift_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    board = chess.Board()
    rows: list[str] = []

    for index, san in enumerate(GAME_SAN):
        ply = index + 1
        mover = "white" if board.turn == chess.WHITE else "black"
        move = board.parse_san(san)  # raises ValueError if our SAN list is wrong
        uci = move.uci()
        fen_before = board.fen()
        is_guess = ply in GUESS_POINT_PLIES
        tag = tag_for(board, move, san)

        if is_guess:
            # master move is best (delta 0); add a placeholder near-equal alt if configured
            evals = {uci: 0}
            if ply in ALT_PENALTY_BY_PLY:
                for alt in board.legal_moves:
                    if alt != move:
                        evals[alt.uci()] = -ALT_PENALTY_BY_PLY[ply]
                        break
            evals_literal = "[" + ", ".join(
                f'{swift_string(u)}: {cp}' for u, cp in evals.items()
            ) + "]"
            annotation = (
                f"Placeholder: {san} is the move here. The real explanation "
                f"(why it works, why common tries fail) comes from the M2 pipeline."
            )
            annotation_literal = swift_string(annotation)
        else:
            evals_literal = "[:]"
            annotation_literal = "nil"

        rows.append(
            f"        ContentMove(ply: {ply}, uci: {swift_string(uci)}, "
            f"san: {swift_string(san)}, fenBefore: {swift_string(fen_before)}, "
            f"mover: .{mover}, isGuessPoint: {str(is_guess).lower()}, "
            f"tags: [.{tag}], annotation: {annotation_literal}, "
            f"candidateEvals: {evals_literal})"
        )
        board.push(move)

    start_fen = chess.Board().fen()
    swift = f"""// GENERATED by pipeline/tools/gen_sample_game.py — do not edit by hand.
// M1 hardcoded sample game. Board data (uci/san/fen) is python-chess-verified legal.
// Evals are placeholders (no engine in M1); real legal_evals come from the M2 pipeline.

import Foundation

enum SampleGames {{
    static let gameOfTheCentury = GameContent(
        id: "byrne-fischer-1956",
        white: "Donald Byrne",
        black: "Robert J. Fischer",
        event: "New York",
        year: 1956,
        result: "0-1",
        heroColor: .black,
        title: {swift_string(TITLE)},
        narrativeIntro: {swift_string(NARRATIVE)},
        startFen: {swift_string(start_fen)},
        moves: [
{",{}".format(chr(10)).join(rows)}
        ]
    )
}}
"""

    out_path = os.path.join(
        os.path.dirname(__file__),
        "..", "..", "App", "Sources", "Features", "GuessSession", "SampleGame.swift",
    )
    out_path = os.path.normpath(out_path)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(swift)

    guess_count = len(GUESS_POINT_PLIES)
    print(f"Wrote {out_path}: {len(GAME_SAN)} plies, {guess_count} guess points.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
