// GENERATED by pipeline/tools/gen_app_game.py from analyzed work-store data.
// Real Stockfish evals + grounded annotations (one-off preview content). Do not edit by hand.

import Foundation

extension SampleGames {
    static let reti = GameContent(
        id: "reti-tartakower-1910-2d0490",
        white: "Reti, Richard",
        black: "Tartakower, Savielly",
        event: "Vienna",
        year: 1910,
        result: "1-0",
        heroColor: .white,
        title: "Reti's Bishop-and-Rook Mate",
        narrativeIntro: "Vienna, 1910. Richard Reti, soon to be a hypermodern pioneer, has White against Savielly Tartakower. Black has just grabbed a knight on e4, expecting a normal game — but the position is about to detonate. You are White.",
        startFen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        moves: [
        ContentMove(ply: 1, uci: "e2e4", san: "e4", fenBefore: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 2, uci: "c7c6", san: "c6", fenBefore: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 3, uci: "d2d4", san: "d4", fenBefore: "rnbqkbnr/pp1ppppp/2p5/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 4, uci: "d7d5", san: "d5", fenBefore: "rnbqkbnr/pp1ppppp/2p5/8/3PP3/8/PPP2PPP/RNBQKBNR b KQkq - 0 2", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 5, uci: "b1c3", san: "Nc3", fenBefore: "rnbqkbnr/pp2pppp/2p5/3p4/3PP3/8/PPP2PPP/RNBQKBNR w KQkq - 0 3", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 6, uci: "d5e4", san: "dxe4", fenBefore: "rnbqkbnr/pp2pppp/2p5/3p4/3PP3/2N5/PPP2PPP/R1BQKBNR b KQkq - 1 3", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 7, uci: "c3e4", san: "Nxe4", fenBefore: "rnbqkbnr/pp2pppp/2p5/8/3Pp3/2N5/PPP2PPP/R1BQKBNR w KQkq - 0 4", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 8, uci: "g8f6", san: "Nf6", fenBefore: "rnbqkbnr/pp2pppp/2p5/8/3PN3/8/PPP2PPP/R1BQKBNR b KQkq - 0 4", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 9, uci: "d1d3", san: "Qd3", fenBefore: "rnbqkb1r/pp2pppp/2p2n2/8/3PN3/8/PPP2PPP/R1BQKBNR w KQkq - 1 5", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 10, uci: "e7e5", san: "e5", fenBefore: "rnbqkb1r/pp2pppp/2p2n2/8/3PN3/3Q4/PPP2PPP/R1B1KBNR b KQkq - 2 5", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 11, uci: "d4e5", san: "dxe5", fenBefore: "rnbqkb1r/pp3ppp/2p2n2/4p3/3PN3/3Q4/PPP2PPP/R1B1KBNR w KQkq - 0 6", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 12, uci: "d8a5", san: "Qa5+", fenBefore: "rnbqkb1r/pp3ppp/2p2n2/4P3/4N3/3Q4/PPP2PPP/R1B1KBNR b KQkq - 0 6", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 13, uci: "c1d2", san: "Bd2", fenBefore: "rnb1kb1r/pp3ppp/2p2n2/q3P3/4N3/3Q4/PPP2PPP/R1B1KBNR w KQkq - 1 7", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 14, uci: "a5e5", san: "Qxe5", fenBefore: "rnb1kb1r/pp3ppp/2p2n2/q3P3/4N3/3Q4/PPPB1PPP/R3KBNR b KQkq - 2 7", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 15, uci: "e1c1", san: "O-O-O", fenBefore: "rnb1kb1r/pp3ppp/2p2n2/4q3/4N3/3Q4/PPPB1PPP/R3KBNR w KQkq - 0 8", mover: .white, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 16, uci: "f6e4", san: "Nxe4", fenBefore: "rnb1kb1r/pp3ppp/2p2n2/4q3/4N3/3Q4/PPPB1PPP/2KR1BNR b kq - 1 8", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 17, uci: "d3d8", san: "Qd8+", fenBefore: "rnb1kb1r/pp3ppp/2p5/4q3/4n3/3Q4/PPPB1PPP/2KR1BNR w kq - 0 9", mover: .white, isGuessPoint: true, tags: [.tactical], annotation: "Qd8+!! hurls the queen onto an empty square to tear open the king. Black is forced to take, and the bishop and rook then hunt the king down to mate. The quiet Re1 keeps an edge but misses the kill; Nf3, Bb4, and Qe2 all let Black escape with the extra piece.", candidateEvals: ["d3d8": 29700, "d1e1": 90, "g1f3": -131, "d2b4": -222, "d3e2": -291, "d2e3": -300, "g1h3": -316, "d2h6": -330, "f2f4": -335, "h2h3": -346, "f1e2": -353, "d3e3": -353, "a2a4": -354, "g2g4": -367, "d2c3": -394, "g1e2": -395, "d2e1": -397, "d3b3": -412, "d2a5": -412, "c2c3": -425, "h2h4": -425, "c1b1": -440, "c2c4": -449, "a2a3": -451, "d3f3": -471, "d3c4": -472, "f2f3": -474, "g2g3": -482, "d3e4": -556, "d2f4": -573, "d2g5": -582, "d3g3": -595, "d3c3": -620, "d3b5": -662, "d3h3": -699, "d3a6": -750, "d3d4": -785, "d3d7": -803, "d3d6": -824, "d3d5": -932, "d3a3": -970, "b2b3": -29900, "b2b4": -29900], difficulty: 916.0),
        ContentMove(ply: 18, uci: "e8d8", san: "Kxd8", fenBefore: "rnbQkb1r/pp3ppp/2p5/4q3/4n3/8/PPPB1PPP/2KR1BNR b kq - 1 9", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 19, uci: "d2g5", san: "Bg5+", fenBefore: "rnbk1b1r/pp3ppp/2p5/4q3/4n3/8/PPPB1PPP/2KR1BNR w - - 0 10", mover: .white, isGuessPoint: true, tags: [.tactical], annotation: "Bg5+!! is the only move that justifies the queen sacrifice. It drives the king to the side, where the bishop delivers mate next while the rook guards the file. Every alternative leaves White a whole queen down: Nf3, Ba5+, Bf4+, and Bc3+ all simply lose.", candidateEvals: ["d2g5": 29800, "g1f3": -493, "d2a5": -508, "d2f4": -624, "d2c3": -630, "f2f4": -706, "f1c4": -753, "d2e3": -760, "f1a6": -798, "g2g3": -807, "d2e1": -819, "g2g4": -824, "h2h4": -824, "c2c3": -839, "f1b5": -848, "d2h6": -855, "a2a4": -857, "f1e2": -858, "a2a3": -859, "g1h3": -861, "c1b1": -866, "h2h3": -867, "d1e1": -882, "d2b4": -886, "g1e2": -887, "f1d3": -904, "c2c4": -925, "f2f3": -963, "b2b4": -29900, "b2b3": -29900], difficulty: 1740.0),
        ContentMove(ply: 20, uci: "d8c7", san: "Kc7", fenBefore: "rnbk1b1r/pp3ppp/2p5/4q1B1/4n3/8/PPP2PPP/2KR1BNR b - - 1 10", mover: .black, isGuessPoint: false, tags: [], annotation: nil, candidateEvals: [:]),
        ContentMove(ply: 21, uci: "g5d8", san: "Bd8#", fenBefore: "rnb2b1r/ppk2ppp/2p5/4q1B1/4n3/8/PPP2PPP/2KR1BNR w - - 2 11", mover: .white, isGuessPoint: true, tags: [.tactical], annotation: "Bd8#!! completes the mate — the dark-squared bishop gives check while the rook on the open file cuts off the king's escape. Be3, Nf3, f4, and Nh3 all throw the game away and leave White a queen down.", candidateEvals: ["g5d8": 29900, "g5e3": -571, "g1f3": -682, "f2f4": -872, "g1h3": -892, "c1b1": -895, "g5h6": -911, "f1d3": -932, "g5d2": -972, "g5e7": -975, "g2g3": -975, "g1e2": -976, "g5f4": -996, "d1d7": -1002, "d1d2": -1006, "g5f6": -1010, "c2c3": -1018, "f1a6": -1028, "f1b5": -1028, "a2a3": -1029, "c2c4": -1036, "f2f3": -1044, "h2h3": -1054, "g2g4": -1055, "d1d3": -1066, "a2a4": -1069, "d1e1": -1074, "d1d5": -1084, "d1d4": -1085, "f1e2": -1147, "d1d8": -1163, "d1d6": -1185, "f1c4": -1251, "g5h4": -1312, "h2h4": -1346, "b2b4": -29900, "b2b3": -29900], difficulty: 1356.0)
        ]
    )
}
